version: '3'
services:
  magic:
    image: data-engineering-zoomcamp:001
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: dezoomcamp.dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ~/.gc/linen-source-mage.json:/home/src/personal-gcp.json
    restart: on-failure:5
