version: 2

sources:
  - name: staging
    database: linen-source-411501
     # For postgres:
      #database: production
    schema: money_diaries_test

      # loaded_at_field: record_loaded_at
    tables:
      - name: blog_entry
      - name: blog_entry__result__content__entries
      - name: blog_entry__result__content__entries__sections__body